<?php

namespace Framework\Http\Constants;

class StatusCodes
{
    const CONTINUE                        = 100;
    const SWITCHING_PROTOCOL              = 101;
    const PROCESSING                      = 102;
    const EARLY_HINTS                     = 103;
    const OK                              = 200;
    const CREATED                         = 201;
    const ACCEPTED                        = 202;
    const NON_AUTHORITATIVE_INFORMATION   = 203;
    const NO_CONTENT                      = 204;
    const RESET_CONTENT                   = 205;
    const PARTIAL_CONTENT                 = 206;
    const MULTI_STATUS                    = 207;
    const ALREADY_REPORTED                = 208;
    const IM_USED                         = 226;
    const MULTIPLE_CHOICE                 = 300;
    const MOVED_PERMANENTLY               = 301;
    const FOUND                           = 302;
    const SEE_OTHER                       = 303;
    const NOT_MODIFIED                    = 304;
    const USE_PROXY                       = 305;
    const TEMPORARY_REDIRECT              = 307;
    const PERMANENT_REDIRECT              = 308;
    const BAD_REQUEST                     = 400;
    const UNAUTHORIZED                    = 401;
    const PAYMENT_REQUIRED                = 402;
    const FORBIDDEN                       = 403;
    const NOT_FOUND                       = 404;
    const METHOD_NOT_ALLOWED              = 405;
    const NOT_ACCEPTABLE                  = 406;
    const PROXY_AUTHENTICATION_REQUIRED   = 407;
    const REQUEST_TIMEOUT                 = 408;
    const CONFLICT                        = 409;
    const GONE                            = 410;
    const LENGTH_REQUIRED                 = 411;
    const PRECONDITION_FAILED             = 412;
    const PAYLOAD_TOO_LARGE               = 413;
    const URI_TOO_LONG                    = 414;
    const UNSUPPORTED_MEDIA_TYPE          = 415;
    const RANGE_NOT_SATISFIABLE           = 416;
    const EXPECTATION_FAILED              = 417;
    const MISDIRECTED_REQUEST             = 421;
    const UNPROCESSABLE_ENTITY            = 422;
    const LOCKED                          = 423;
    const FAILED_DEPENDENCY               = 424;
    const TOO_EARLY                       = 425;
    const UPGRADE_REQUIRED                = 426;
    const PRECONDITION_REQUIRED           = 428;
    const TOO_MANY_REQUESTS               = 429;
    const REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
    const UNAVAILABLE_FOR_LEGAL_REASONS   = 451;
    const INTERNAL_SERVER_ERROR           = 500;
    const NOT_IMPLEMENTED                 = 501;
    const BAD_GATEWAY                     = 502;
    const SERVICE_UNAVAILABLE             = 503;
    const GATEWAY_TIMEOUT                 = 504;
    const HTTP_VERSION_NOT_SUPPORTED      = 505;
    const VARIANT_ALSO_NEGOTIATES         = 506;
    const INSUFFICIENT_STORAGE            = 507;
    const LOOP_DETECTED                   = 508;
    const NOT_EXTENDED                    = 510;
    const NETWORK_AUTHENTICATION_REQUIRED = 511;
}



//enum StatusCodes: int
//{
//    case CONTINUE = 100;
//    case SWITCHING_PROTOCOL = 101;
//    case PROCESSING = 102;
//    case EARLY_HINTS = 103;
//    case OK = 200;
//    case CREATED = 201;
//    case ACCEPTED = 202;
//    case NON_AUTHORITATIVE_INFORMATION = 203;
//    case NO_CONTENT = 204;
//    case RESET_CONTENT = 205;
//    case PARTIAL_CONTENT = 206;
//    case MULTI_STATUS = 207;
//    case ALREADY_REPORTED = 208;
//    case IM_USED = 226;
//    case MULTIPLE_CHOICE = 300;
//    case MOVED_PERMANENTLY = 301;
//    case FOUND = 302;
//    case SEE_OTHER = 303;
//    case NOT_MODIFIED = 304;
//    case USE_PROXY = 305;
//    case TEMPORARY_REDIRECT = 307;
//    case PERMANENT_REDIRECT = 308;
//    case BAD_REQUEST = 400;
//    case UNAUTHORIZED = 401;
//    case PAYMENT_REQUIRED = 402;
//    case FORBIDDEN = 403;
//    case NOT_FOUND = 404;
//    case METHOD_NOT_ALLOWED = 405;
//    case NOT_ACCEPTABLE = 406;
//    case PROXY_AUTHENTICATION_REQUIRED = 407;
//    case REQUEST_TIMEOUT = 408;
//    case CONFLICT = 409;
//    case GONE = 410;
//    case LENGTH_REQUIRED = 411;
//    case PRECONDITION_FAILED = 412;
//    case PAYLOAD_TOO_LARGE = 413;
//    case URI_TOO_LONG = 414;
//    case UNSUPPORTED_MEDIA_TYPE = 415;
//    case RANGE_NOT_SATISFIABLE = 416;
//    case EXPECTATION_FAILED = 417;
//    case MISDIRECTED_REQUEST = 421;
//    case UNPROCESSABLE_ENTITY = 422;
//    case LOCKED = 423;
//    case FAILED_DEPENDENCY = 424;
//    case TOO_EARLY = 425;
//    case UPGRADE_REQUIRED = 426;
//    case PRECONDITION_REQUIRED = 428;
//    case TOO_MANY_REQUESTS = 429;
//    case REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
//    case UNAVAILABLE_FOR_LEGAL_REASONS = 451;
//    case INTERNAL_SERVER_ERROR = 500;
//    case NOT_IMPLEMENTED = 501;
//    case BAD_GATEWAY = 502;
//    case SERVICE_UNAVAILABLE = 503;
//    case GATEWAY_TIMEOUT = 504;
//    case HTTP_VERSION_NOT_SUPPORTED = 505;
//    case VARIANT_ALSO_NEGOTIATES = 506;
//    case INSUFFICIENT_STORAGE = 507;
//    case LOOP_DETECTED = 508;
//    case NOT_EXTENDED = 510;
//    case NETWORK_AUTHENTICATION_REQUIRED = 511;
//}
